# TD - Préparation et nettoyage des données avec Pandas & NumPy

## Auteur
Joseph DELNORD

## Module
Introduction à l'IA et au Machine Learning pour les DEV

## Objectif

Mise en œuvre des techniques de préparation de données :

- Manipulation de Series Pandas
- Chargement de fichiers CSV
- Gestion des valeurs manquantes
- Nettoyage des données
- Imputation avec Pandas
- Imputation avec Scikit-Learn
- Élaboration d'une stratégie de nettoyage

In [1]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer

## Exercice 1 - Manipulation d'une Series

In [2]:
sports = {
    'bask': 'BasketBall',
    'hand': 'HandBall',
    'snow': 'Snowsport',
    'base': 'BaseBall',
    'swim': 'Swimming'
}

sIndex = pd.Series(sports)

display(sIndex)

bask    BasketBall
hand      HandBall
snow     Snowsport
base      BaseBall
swim      Swimming
dtype: str

In [3]:
# Question 1

print(sIndex.iloc[1])

print(sIndex.loc['swim'])

HandBall
Swimming

In [4]:
# Question 2

sIndex.str.upper()

bask    BASKETBALL
hand      HANDBALL
snow     SNOWSPORT
base      BASEBALL
swim      SWIMMING
dtype: str

In [5]:
# Question 3

resultat = []

for sport in sIndex:
    resultat.append(sport.upper())

resultat

['BASKETBALL', 'HANDBALL', 'SNOWSPORT', 'BASEBALL', 'SWIMMING']

In [8]:
# Question 4

%timeit sIndex.str.upper()

76.9 μs ± 2.44 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

### Conclusion

La solution Pandas est plus rapide grâce à la vectorisation.

## Exercice 2 - Chargement d'un CSV

In [9]:
Clients_Data = pd.read_csv("../data/Custemers.csv")

In [10]:
Clients_Data.shape

(10000, 15)

In [11]:
Clients_Data.head()

,name,address,city,state,zip,phone,email,work,work address,work city,work state,work zipcode,work phone,work email,account created on
0,Deonte Stark,278 Mueller Plains,North Euna,Alabama,03404-4384,(180)940-9676x4495,shanna73@hotmail.com,Hahn-Mayer,8177 Weber Throughway Apt. 341,Jaronton,Maine,51589-1424,01240240340,heller.kirstin@glover.com,2001-09-06 06:15:24
1,Faustino Boyer,70244 Skiles Falls Suite 030,North Altohaven,California,01522-1310,(308)699-6239x81011,ferrell81@gmail.com,Buckridge Inc,236 Kessler Center,New Gavynshire,Missouri,52234-6972,(486)896-6855x446,esta.dicki@bechtelar.com,1983-04-25
2,"Eddy Bogisich,33431 Dollie Squares Apt. 654,Po...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mervyn Kreiger,376 Dorinda Stream,Shaniquafort,South Carolina,39347-4438,869-985-6299,emmerich.griselda@hotmail.com,Witting PLC,521 Kemmer Manors,Nerytown,Kentucky,68774,(212)169-8190,greyson39@purdy.com,1971-04-27 14:05:06
4,"Katlyn Doyle,4650 Beer Crossing Suite 848,Nort...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
Clients_Data.columns

Index(['name', 'address', 'city', 'state', 'zip', 'phone', 'email', 'work',
       'work address', 'work city', 'work state', 'work zipcode', 'work phone',
       'work email', 'account created on', 'firstname', 'lastname'],
      dtype='str')

## Exercice 3 - Détection des valeurs manquantes

In [13]:
Clients_Data.isnull().sum()

name                    81
address               3365
city                  3374
state                 3365
zip                   3362
phone                 3366
email                 3363
work                  3390
work address          3383
work city             3378
work state            3390
work zipcode          3378
work phone            3377
work email            3359
account created on    3368
dtype: int64

In [14]:
Clients_Data.isnull().mean()*100

name                   0.81
address               33.65
city                  33.74
state                 33.65
zip                   33.62
phone                 33.66
email                 33.63
work                  33.90
work address          33.83
work city             33.78
work state            33.90
work zipcode          33.78
work phone            33.77
work email            33.59
account created on    33.68
dtype: float64

In [15]:
Clients_Data[
    Clients_Data['name'].isnull()
]

,name,address,city,state,zip,phone,email,work,work address,work city,work state,work zipcode,work phone,work email,account created on
148,NaN,558 Brycen Mission Suite 152,Cristmouth,Arkansas,52585-7480,+03(6)2449148729,corene08@gmail.com,Braun PLC,8795 Carissa Land Apt. 884,South Arachester,New Mexico,68070-4086,09359769734,hezzie.hettinger@mcglynnlarson.com,1999-12-12
273,NaN,0481 Sanford Lake Apt. 439,Bashirianberg,North Carolina,61948-9865,(967)713-7747x7329,hermiston.jenniffer@hotmail.com,Grant LLC,7375 Lynn Fork,Wuckerthaven,Ohio,89342-4989,419-132-5389,colin.walsh@hane.com,1995-08-07 19:52:30
300,NaN,38689 Kimora Groves Suite 807,New Nadiahaven,Vermont,99133-2546,595.341.7775x50639,sfritsch@yahoo.com,Purdy-Farrell,29365 Nyah Flats,West Isabella,Florida,06342,+66(4)7117753075,ocrooks@mohr.net,1975-04-07
330,NaN,077 Walsh Summit Suite 123,Rogahnfurt,Indiana,81369,+38(1)3931574807,tdenesik@hotmail.com,Corwin-Fahey,717 Karol Stravenue Apt. 964,Trantowhaven,Utah,49873-6641,882.577.0021x2495,mschaden@gerholdschultz.net,03/10/2010
467,NaN,87140 Loma Crescent,North Dixieport,Michigan,32196-8397,+65(0)2946604451,lucille69@gmail.com,Monahan Ltd,99220 Murphy Motorway,East Reyhaven,Rhode Island,50641,773.245.8906,parisian.willard@feil.org,04/29/1986
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9316,NaN,054 Aubrie Corners,East Genevieve,New Hampshire,92371,296-242-9406x586,enrico.kuvalis@yahoo.com,Schneider LLC,53056 Gaige Motorway,North Audriana,Arkansas,73816,605.101.0879,cephus.conroy@schroeder.com,01/21/2000
9487,NaN,9957 Rempel Wells Apt. 081,New Micky,Alabama,24013,522-665-0735,rylan47@hotmail.com,Bergnaum and Sons,60120 Klocko Alley Apt. 615,Adalineport,Maryland,37182-8209,289.393.5802x9949,mwolf@corwin.net,2000-09-07
9745,NaN,6277 Schneider Common Suite 939,Port Aura,North Dakota,10127,127.858.7550,kacy29@gmail.com,Becker PLC,186 Armstrong Lakes,East Rosalyn,Ohio,07576,1-924-436-1559x850,kunde.carry@auerweimann.org,1995-08-13 11:03:45
9816,NaN,986 Brianne Shoals,Port Wilbertstad,Mississippi,99396,953.475.7297x373,ritchie.hadley@yahoo.com,Kautzer-Batz,22243 Feil Terrace Suite 469,New Catofurt,Wisconsin,62178,09723145605,thompson.eulalie@mann.com,1970-01-27 16:26:56
9834,NaN,19233 Kreiger Meadow,Kleinville,Michigan,42537-0382,(894)710-7706x071,hjalmer14@hotmail.com,Beer-Ledner,48801 Bobbye Roads,West Tylor,Arkansas,60338,849.567.9201x682,hsatterfield@bradtke.com,2015-10-13 23:24:40

In [16]:
Clients_Data.dropna(
    how="all"
)

,name,address,city,state,zip,phone,email,work,work address,work city,work state,work zipcode,work phone,work email,account created on
0,Deonte Stark,278 Mueller Plains,North Euna,Alabama,03404-4384,(180)940-9676x4495,shanna73@hotmail.com,Hahn-Mayer,8177 Weber Throughway Apt. 341,Jaronton,Maine,51589-1424,01240240340,heller.kirstin@glover.com,2001-09-06 06:15:24
1,Faustino Boyer,70244 Skiles Falls Suite 030,North Altohaven,California,01522-1310,(308)699-6239x81011,ferrell81@gmail.com,Buckridge Inc,236 Kessler Center,New Gavynshire,Missouri,52234-6972,(486)896-6855x446,esta.dicki@bechtelar.com,1983-04-25
2,"Eddy Bogisich,33431 Dollie Squares Apt. 654,Po...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mervyn Kreiger,376 Dorinda Stream,Shaniquafort,South Carolina,39347-4438,869-985-6299,emmerich.griselda@hotmail.com,Witting PLC,521 Kemmer Manors,Nerytown,Kentucky,68774,(212)169-8190,greyson39@purdy.com,1971-04-27 14:05:06
4,"Katlyn Doyle,4650 Beer Crossing Suite 848,Nort...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Ciera Wunsch,25198 Fernando Isle Suite 175,South Pricillashire,Colorado,53222-8926,005-769-2290x3662,shannon.beatty@gmail.com,Metz-Kub,28254 Nikolaus Plains,West Emmitthaven,Minnesota,34939-5981,(154)316-2907x520,clemente.dach@leannon.com,1986-11-14
9996,Beula Bauch,800 Keebler Stream,East Denise,Maine,33693,933.047.0305,steuber.zakary@hotmail.com,Barrows Inc,35083 Champlin Keys Suite 030,Port Yulisa,Rhode Island,35745,(148)771-5153x521,windler.trudi@shanahanhagenes.org,2013-11-02 20:50:10
9997,Garvin Runolfsson,4844 Dietrich Islands Suite 457,Auerport,Michigan,34497,312.046.9856,nwehner@hotmail.com,Braun Inc,7514 Samiyah Brooks,West Ham,Texas,90804,388-879-8433x7099,stamm.erlene@stoltenberg.org,2008-04-13
9998,Hildegarde Gleichner,96841 Predovic Locks,New Knute,Rhode Island,88719-7033,269-922-1275,ksatterfield@yahoo.com,Turcotte LLC,NaN,Medhurstside,Oregon,20523-8984,863.095.3340x2593,coby06@kulasbogan.com,1990-02-20
9999,"Rhett Spinka,87035 Solon Prairie,Zelmahaven,Ha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
Clients_Data.dropna(
    axis=0
)

,name,address,city,state,zip,phone,email,work,work address,work city,work state,work zipcode,work phone,work email,account created on
0,Deonte Stark,278 Mueller Plains,North Euna,Alabama,03404-4384,(180)940-9676x4495,shanna73@hotmail.com,Hahn-Mayer,8177 Weber Throughway Apt. 341,Jaronton,Maine,51589-1424,01240240340,heller.kirstin@glover.com,2001-09-06 06:15:24
1,Faustino Boyer,70244 Skiles Falls Suite 030,North Altohaven,California,01522-1310,(308)699-6239x81011,ferrell81@gmail.com,Buckridge Inc,236 Kessler Center,New Gavynshire,Missouri,52234-6972,(486)896-6855x446,esta.dicki@bechtelar.com,1983-04-25
3,Mervyn Kreiger,376 Dorinda Stream,Shaniquafort,South Carolina,39347-4438,869-985-6299,emmerich.griselda@hotmail.com,Witting PLC,521 Kemmer Manors,Nerytown,Kentucky,68774,(212)169-8190,greyson39@purdy.com,1971-04-27 14:05:06
5,Daquan Leffler,43142 Howell Ports Apt. 953,West Emory,Connecticut,08086-5571,874-576-0739,natosha.kutch@yahoo.com,Christiansen Ltd,3136 Jered Junction Suite 993,West Mallie,New Hampshire,40778-7891,215.605.7824x844,anderson.gifford@nader.com,2014-01-15 23:15:43
6,Jace Konopelski,963 Senger Points Apt. 992,Lake Fonda,North Dakota,15581,(083)182-4626x8012,langosh.mathilde@hotmail.com,Glover-Howe,87986 Harvey Islands,South Zackary,Kentucky,75232-9391,(270)125-2639,kassulke.fate@hills.com,05/20/2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,Tawnya Williamson,4160 Welch Roads,Amasahaven,Maine,76161,1-468-320-0246x8915,doreilly@yahoo.com,Schuster-Lemke,82853 Watsica View,South Jaydan,Georgia,54467-3704,264-477-5271,donell95@wilderman.com,1974-07-22
9993,Cayla Gleason,505 Rogahn Trafficway,New Sabastian,Tennessee,56989-4233,(578)118-9244x85865,mtorp@gmail.com,Morissette Group,484 Lubowitz Inlet Suite 138,East Sannieland,North Carolina,66018,892-930-2586x31401,bina.pagac@johns.com,1996-04-08
9995,Ciera Wunsch,25198 Fernando Isle Suite 175,South Pricillashire,Colorado,53222-8926,005-769-2290x3662,shannon.beatty@gmail.com,Metz-Kub,28254 Nikolaus Plains,West Emmitthaven,Minnesota,34939-5981,(154)316-2907x520,clemente.dach@leannon.com,1986-11-14
9996,Beula Bauch,800 Keebler Stream,East Denise,Maine,33693,933.047.0305,steuber.zakary@hotmail.com,Barrows Inc,35083 Champlin Keys Suite 030,Port Yulisa,Rhode Island,35745,(148)771-5153x521,windler.trudi@shanahanhagenes.org,2013-11-02 20:50:10
9997,Garvin Runolfsson,4844 Dietrich Islands Suite 457,Auerport,Michigan,34497,312.046.9856,nwehner@hotmail.com,Braun Inc,7514 Samiyah Brooks,West Ham,Texas,90804,388-879-8433x7099,stamm.erlene@stoltenberg.org,2008-04-13

### Observation

La suppression directe des lignes peut entraîner une perte importante d'informations.

## Exercice 4 - Vérification des types et nettoyage

In [62]:
print(Clients_Data.dtypes)

name                  str
address               str
city                  str
state                 str
zip                   str
phone                 str
email                 str
work                  str
work address          str
work city             str
work state            str
work zipcode          str
work phone            str
work email            str
account created on    str
firstname             str
lastname              str
dtype: object

In [18]:
Clients_Data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                9919 non-null   str
 1   address             6635 non-null   str
 2   city                6626 non-null   str
 3   state               6635 non-null   str
 4   zip                 6638 non-null   str
 5   phone               6634 non-null   str
 6   email               6637 non-null   str
 7   work                6610 non-null   str
 8   work address        6617 non-null   str
 9   work city           6622 non-null   str
 10  work state          6610 non-null   str
 11  work zipcode        6622 non-null   str
 12  work phone          6623 non-null   str
 13  work email          6641 non-null   str
 14  account created on  6632 non-null   str
dtypes: str(15)
memory usage: 1.1 MB

In [19]:
Clients_Data[
    ["firstname","lastname"]
] = (
    Clients_Data["name"]
    .str.split(
        " ",
        n=1,
        expand=True
    )
)

In [20]:
Clients_Data.head()

,name,address,city,state,zip,phone,email,work,work address,work city,work state,work zipcode,work phone,work email,account created on,firstname,lastname
0,Deonte Stark,278 Mueller Plains,North Euna,Alabama,03404-4384,(180)940-9676x4495,shanna73@hotmail.com,Hahn-Mayer,8177 Weber Throughway Apt. 341,Jaronton,Maine,51589-1424,01240240340,heller.kirstin@glover.com,2001-09-06 06:15:24,Deonte,Stark
1,Faustino Boyer,70244 Skiles Falls Suite 030,North Altohaven,California,01522-1310,(308)699-6239x81011,ferrell81@gmail.com,Buckridge Inc,236 Kessler Center,New Gavynshire,Missouri,52234-6972,(486)896-6855x446,esta.dicki@bechtelar.com,1983-04-25,Faustino,Boyer
2,"Eddy Bogisich,33431 Dollie Squares Apt. 654,Po...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eddy,"Bogisich,33431 Dollie Squares Apt. 654,Port Ca..."
3,Mervyn Kreiger,376 Dorinda Stream,Shaniquafort,South Carolina,39347-4438,869-985-6299,emmerich.griselda@hotmail.com,Witting PLC,521 Kemmer Manors,Nerytown,Kentucky,68774,(212)169-8190,greyson39@purdy.com,1971-04-27 14:05:06,Mervyn,Kreiger
4,"Katlyn Doyle,4650 Beer Crossing Suite 848,Nort...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Katlyn,"Doyle,4650 Beer Crossing Suite 848,North Dells..."

In [64]:
Clients_Data["lastname"].str.len()

2       239
4       239
9       223
10      271
13      213
       ...
9987    240
9994    249
9997     17
9998     20
9999    245
Name: lastname, Length: 3627, dtype: int64

In [68]:
Clients_Data = Clients_Data[
    Clients_Data["lastname"].str.len() > 16
]

In [70]:
print(
    Clients_Data
)

                                                   name  \
2     Eddy Bogisich,33431 Dollie Squares Apt. 654,Po...
4     Katlyn Doyle,4650 Beer Crossing Suite 848,Nort...
9     Weston Ebert,03552 Lehner Ridge,New Attilio,Ha...
10    Joshuah Mosciski,31085 Schmitt Parkways Apt. 9...
13     Jovanny Armstrong,7334 Kris Flat,,Florida,792...
...                                                 ...
9987  Mervyn Krajcik,34259 Pagac Pike,Schmittland,Ok...
9994  Wiley Bradtke,9508 Simonis Crossing Suite 502,...
9997                                  Garvin Runolfsson
9998                               Hildegarde Gleichner
9999  Rhett Spinka,87035 Solon Prairie,Zelmahaven,Ha...

                              address       city         state         zip  \
2                                 NaN        NaN           NaN         NaN
4                                 NaN        NaN           NaN         NaN
9                                 NaN        NaN           NaN         NaN
10                                NaN        NaN           NaN         NaN
13                                NaN        NaN           NaN         NaN
...                               ...        ...           ...         ...
9987                              NaN        NaN           NaN         NaN
9994                              NaN        NaN           NaN         NaN
9997  4844 Dietrich Islands Suite 457   Auerport      Michigan       34497
9998             96841 Predovic Locks  New Knute  Rhode Island  88719-7033
9999                              NaN        NaN           NaN         NaN

             phone                   email          work         work address  \
2              NaN                     NaN           NaN                  NaN
4              NaN                     NaN           NaN                  NaN
9              NaN                     NaN           NaN                  NaN
10             NaN                     NaN           NaN                  NaN
13             NaN                     NaN           NaN                  NaN
...            ...                     ...           ...                  ...
9987           NaN                     NaN           NaN                  NaN
9994           NaN                     NaN           NaN                  NaN
9997  312.046.9856     nwehner@hotmail.com     Braun Inc  7514 Samiyah Brooks
9998  269-922-1275  ksatterfield@yahoo.com  Turcotte LLC                  NaN
9999           NaN                     NaN           NaN                  NaN

         work city work state work zipcode         work phone  \
2              NaN        NaN          NaN                NaN
4              NaN        NaN          NaN                NaN
9              NaN        NaN          NaN                NaN
10             NaN        NaN          NaN                NaN
13             NaN        NaN          NaN                NaN
...            ...        ...          ...                ...
9987           NaN        NaN          NaN                NaN
9994           NaN        NaN          NaN                NaN
9997      West Ham      Texas        90804  388-879-8433x7099
9998  Medhurstside     Oregon   20523-8984  863.095.3340x2593
9999           NaN        NaN          NaN                NaN

                        work email account created on firstname  \
2                              NaN                NaN      Eddy
4                              NaN                NaN    Katlyn
9                              NaN                NaN    Weston
10                             NaN                NaN   Joshuah
13                             NaN                NaN
...                            ...                ...       ...
9987                           NaN                NaN    Mervyn
9994                           NaN                NaN     Wiley
9997  stamm.erlene@stoltenberg.org         2008-04-13
9998         coby06@kulasbogan.com         1990-02-20
9999                           NaN                NaN     Rhett

                                               lastname
2     Bogisich,33431 Dollie Squares Apt. 654,Port Ca...
4     Doyle,4650 Beer Crossing Suite 848,North Dells...
9     Ebert,03552 Lehner Ridge,New Attilio,Hawaii,35...
10    Mosciski,31085 Schmitt Parkways Apt. 957,Dibbe...
13    Jovanny Armstrong,7334 Kris Flat,,Florida,7922...
...                                                 ...
9987  Krajcik,34259 Pagac Pike,Schmittland,Oklahoma,...
9994  Bradtke,9508 Simonis Crossing Suite 502,East H...
9997                                  Garvin Runolfsson
9998                               Hildegarde Gleichner
9999  Spinka,87035 Solon Prairie,Zelmahaven,Hawaii,3...

[3627 rows x 17 columns]

## Exercice 5 — Imputation pour traiter les données manquantes

In [23]:
origin_Data = pd.read_csv(
    "../data/melb_data.csv"
)

In [24]:
origin_Data.info()

<class 'pandas.DataFrame'>
RangeIndex: 18396 entries, 0 to 18395
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     18396 non-null  int64
 1   Suburb         18396 non-null  str
 2   Address        18396 non-null  str
 3   Rooms          18396 non-null  int64
 4   Type           18396 non-null  str
 5   Price          18396 non-null  float64
 6   Method         18396 non-null  str
 7   SellerG        18396 non-null  str
 8   Date           18396 non-null  str
 9   Distance       18395 non-null  float64
 10  Postcode       18395 non-null  float64
 11  Bedroom2       14927 non-null  float64
 12  Bathroom       14925 non-null  float64
 13  Car            14820 non-null  float64
 14  Landsize       13603 non-null  float64
 15  BuildingArea   7762 non-null   float64
 16  YearBuilt      8958 non-null   float64
 17  CouncilArea    12233 non-null  str
 18  Lattitude      15064 non-null  float64
 19  Longtitude     15064 non-null  float64
 20  Regionname     18395 non-null  str
 21  Propertycount  18395 non-null  float64
dtypes: float64(12), int64(2), str(8)
memory usage: 3.1 MB

In [25]:
origin_Data.shape

(18396, 22)

In [26]:
origin_Data.isnull().sum()

Unnamed: 0           0
Suburb               0
Address              0
Rooms                0
Type                 0
Price                0
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          3469
Bathroom          3471
Car               3576
Landsize          4793
BuildingArea     10634
YearBuilt         9438
CouncilArea       6163
Lattitude         3332
Longtitude        3332
Regionname           1
Propertycount        1
dtype: int64

In [27]:
origin_Data.isnull().sum(axis=1)

0        2
1        0
2        0
3        2
4        0
        ..
18391    2
18392    1
18393    4
18394    1
18395    2
Length: 18396, dtype: int64

In [28]:
def missing_columns(originDB):

    colsWithMissing = [
        col
        for col in originDB.columns
        if originDB[col].isnull().any()
    ]

    reduced_original_data = originDB.drop(
        colsWithMissing,
        axis=1
    )

    return colsWithMissing, reduced_original_data

In [29]:
colsWithMissing, reducedData = (
    missing_columns(origin_Data)
)

colsWithMissing

['Distance',
 'Postcode',
 'Bedroom2',
 'Bathroom',
 'Car',
 'Landsize',
 'BuildingArea',
 'YearBuilt',
 'CouncilArea',
 'Lattitude',
 'Longtitude',
 'Regionname',
 'Propertycount']

In [30]:
origin_Data.isnull().mean()*100

Unnamed: 0        0.000000
Suburb            0.000000
Address           0.000000
Rooms             0.000000
Type              0.000000
Price             0.000000
Method            0.000000
SellerG           0.000000
Date              0.000000
Distance          0.005436
Postcode          0.005436
Bedroom2         18.857360
Bathroom         18.868232
Car              19.439008
Landsize         26.054577
BuildingArea     57.806045
YearBuilt        51.304631
CouncilArea      33.501848
Lattitude        18.112633
Longtitude       18.112633
Regionname        0.005436
Propertycount     0.005436
dtype: float64

In [31]:
origin_Data.isnull().mean(axis=1)*100

0         9.090909
1         0.000000
2         0.000000
3         9.090909
4         0.000000
           ...
18391     9.090909
18392     4.545455
18393    18.181818
18394     4.545455
18395     9.090909
Length: 18396, dtype: float64

In [32]:
new_Data = origin_Data[
    origin_Data.isnull().mean(axis=1)*100 <= 5
]

In [69]:
print(
    new_Data
)

       Unnamed: 0        Suburb          Address  Rooms Type      Price  \
1               2    Abbotsford  25 Bloomburg St      2    h  1035000.0
2               4    Abbotsford     5 Charles St      3    h  1465000.0
4               6    Abbotsford      55a Park St      4    h  1600000.0
6              11    Abbotsford     124 Yarra St      3    h  1876000.0
7              14    Abbotsford    98 Charles St      2    h  1636000.0
...           ...           ...              ...    ...  ...        ...
18382       23527      Watsonia    76 Kenmare St      2    h   650000.0
18384       23532      Werribee      5 Nuragi Ct      4    h   635000.0
18389       23538  Williamstown    77 Merrett Dr      3    h  1031000.0
18392       23541  Williamstown     96 Verdon St      4    h  2500000.0
18394       23545    Yarraville       6 Agnes St      4    h  1285000.0

      Method        SellerG        Date  Distance  ...  Bathroom  Car  \
1          S         Biggin   4/02/2016       2.5  ...       1.0  0.0
2         SP         Biggin   4/03/2017       2.5  ...       2.0  0.0
4         VB         Nelson   4/06/2016       2.5  ...       1.0  2.0
6          S         Nelson   7/05/2016       2.5  ...       2.0  0.0
7          S         Nelson   8/10/2016       2.5  ...       1.0  2.0
...      ...            ...         ...       ...  ...       ...  ...
18382     PI       Morrison  26/08/2017      14.5  ...       1.0  1.0
18384      S  hockingstuart  26/08/2017      14.7  ...       2.0  1.0
18389     SP       Williams  26/08/2017       6.8  ...       2.0  2.0
18392     PI        Sweeney  26/08/2017       6.8  ...       1.0  5.0
18394     SP        Village  26/08/2017       6.3  ...       1.0  1.0

       Landsize  BuildingArea  YearBuilt  CouncilArea  Lattitude Longtitude  \
1         156.0          79.0     1900.0        Yarra  -37.80790  144.99340
2         134.0         150.0     1900.0        Yarra  -37.80930  144.99440
4         120.0         142.0     2014.0        Yarra  -37.80720  144.99410
6         245.0         210.0     1910.0        Yarra  -37.80240  144.99930
7         256.0         107.0     1890.0        Yarra  -37.80600  144.99540
...         ...           ...        ...          ...        ...        ...
18382     210.0          79.0     2006.0          NaN  -37.70657  145.07878
18384     662.0         172.0     1980.0          NaN  -37.89327  144.64789
18389     333.0         133.0     1995.0          NaN  -37.85927  144.87904
18392     866.0         157.0     1920.0          NaN  -37.85908  144.89299
18394     362.0         112.0     1920.0          NaN  -37.81188  144.88449

                  Regionname  Propertycount
1      Northern Metropolitan         4019.0
2      Northern Metropolitan         4019.0
4      Northern Metropolitan         4019.0
6      Northern Metropolitan         4019.0
7      Northern Metropolitan         4019.0
...                      ...            ...
18382  Northern Metropolitan         2329.0
18384   Western Metropolitan        16166.0
18389   Western Metropolitan         6380.0
18392   Western Metropolitan         6380.0
18394   Western Metropolitan         6543.0

[8332 rows x 22 columns]

## Exercice 6 - Imputation avec SimpleImputer

In [33]:
origin_Data_num = (
    origin_Data.select_dtypes(
        include=['number']
    )
)

In [34]:
imputer = SimpleImputer(
    strategy='mean'
)

In [35]:
imputer.fit(origin_Data_num)

SimpleImputer()

In [36]:
imputer.statistics_

array([ 1.18267871e+04,  2.93504023e+00,  1.05669746e+06,  1.03899864e+01,
        3.10714015e+03,  2.91304348e+00,  1.53849246e+00,  1.61551957e+00,
        5.58116371e+02,  1.51220219e+02,  1.96588000e+03, -3.78098491e+01,
        1.44996338e+02,  7.51797527e+03])

In [37]:
transform_data = (
    imputer.transform(
        origin_Data_num
    )
)

In [38]:
df_transform = pd.DataFrame(
    transform_data,
    columns=origin_Data_num.columns,
    index=origin_Data_num.index
)

In [39]:
df_transform.head()

,Unnamed: 0,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
0,1.0,2.0,1480000.0,2.5,3067.0,2.0,1.0,1.0,202.0,151.220219,1965.879996,-37.7996,144.9984,4019.0
1,2.0,2.0,1035000.0,2.5,3067.0,2.0,1.0,0.0,156.0,79.000000,1900.000000,-37.8079,144.9934,4019.0
2,4.0,3.0,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.0,150.000000,1900.000000,-37.8093,144.9944,4019.0
3,5.0,3.0,850000.0,2.5,3067.0,3.0,2.0,1.0,94.0,151.220219,1965.879996,-37.7969,144.9969,4019.0
4,6.0,4.0,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.0,142.000000,2014.000000,-37.8072,144.9941,4019.0

## Exercice 7 - Nettoyage du dataset Olympics

In [40]:
olympics = pd.read_csv(
    "../data/olympics.csv"
)

In [41]:
olympics.info()

<class 'pandas.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       147 non-null    str
 1   1       148 non-null    str
 2   2       148 non-null    str
 3   3       148 non-null    str
 4   4       148 non-null    str
 5   5       148 non-null    str
 6   6       148 non-null    str
 7   7       148 non-null    str
 8   8       148 non-null    str
 9   9       148 non-null    str
 10  10      148 non-null    str
 11  11      148 non-null    str
 12  12      148 non-null    str
 13  13      148 non-null    str
 14  14      148 non-null    str
 15  15      148 non-null    str
dtypes: str(16)
memory usage: 18.6 KB

In [42]:
olympics.shape

(148, 16)

In [43]:
olympics.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !,02 !,03 !,Total,№ Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12

In [44]:
olympics.isnull().sum()

0     1
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

In [46]:
olympics.duplicated().sum()

np.int64(0)

In [47]:
olympics.drop_duplicates(
    inplace=True
)

In [48]:
olympics.dropna(
    how="all",
    inplace=True
)

### Stratégie appliquée

- Vérification de la structure
- Vérification des types
- Détection des valeurs manquantes
- Suppression des doublons
- Suppression des lignes totalement vides

## Exercice 7 - Nettoyage du dataset Flicker

In [49]:
flicker = pd.read_csv(
    "../data/flicker.csv"
)

In [50]:
flicker.info()

<class 'pandas.DataFrame'>
RangeIndex: 8287 entries, 0 to 8286
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Identifier              8287 non-null   int64
 1   Edition Statement       773 non-null    str
 2   Place of Publication    8287 non-null   str
 3   Date of Publication     8106 non-null   str
 4   Publisher               4092 non-null   str
 5   Title                   8287 non-null   str
 6   Author                  6509 non-null   str
 7   Contributors            8287 non-null   str
 8   Corporate Author        0 non-null      float64
 9   Corporate Contributors  0 non-null      float64
 10  Former owner            1 non-null      str
 11  Engraver                0 non-null      float64
 12  Issuance type           8287 non-null   str
 13  Flickr URL              8287 non-null   str
 14  Shelfmarks              8287 non-null   str
dtypes: float64(3), int64(1), str(11)
memory usage: 971.3 KB

In [51]:
flicker.shape

(8287, 15)

In [52]:
flicker.head()

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [53]:
flicker.isnull().sum()

Identifier                   0
Edition Statement         7514
Place of Publication         0
Date of Publication        181
Publisher                 4195
Title                        0
Author                    1778
Contributors                 0
Corporate Author          8287
Corporate Contributors    8287
Former owner              8286
Engraver                  8287
Issuance type                0
Flickr URL                   0
Shelfmarks                   0
dtype: int64

In [54]:
flicker.duplicated().sum()

np.int64(0)

In [55]:
flicker.dropna(
    how="all",
    inplace=True
)

In [57]:
num_cols = flicker.select_dtypes(
    include="number"
)

num_cols = num_cols.dropna(
    axis=1,
    how="all"
)

imputer = SimpleImputer(
    strategy="mean"
)

result = imputer.fit_transform(
    num_cols
)

num_cols_clean = pd.DataFrame(
    result,
    columns=num_cols.columns,
    index=num_cols.index
)

num_cols_clean.head()

   Identifier
0       206.0
1       216.0
2       218.0
3       472.0
4       480.0

### Conclusion générale

Les datasets ont été explorés, nettoyés et préparés pour être utilisés dans un pipeline de Machine Learning.

Les principales étapes ont été :

- Analyse exploratoire
- Détection des valeurs manquantes
- Nettoyage
- Imputation
- Vérification finale de la qualité des données